rgleason/weather_routing_pi

- WeatherRouting.fbp
- cmake/PluginConfigure.cmake
- cmake/wxWTranslateCatalog.h.in
- po/fr.po
- po/weather_routing_pi.pot
- src/.gitignore
- src/ReportDialog.cpp
- src/SettingsDialog.cpp
- src/WeatherRouting.cpp
- src/WeatherRoutingUI.cpp
- src/WeatherRoutingUI.h
> Pot and french updates

- WeatherRouting.fbp
- src/WeatherRoutingUI.cpp
- src/WeatherRoutingUI.h
> Fix configuration dialog layout

- src/WeatherRouting.cpp
> add missing end point in track export and use right time for waypoint

- CMakeLists.txt
- src/icons.cpp
- src/icons.h
- src/weather_routing_pi.cpp
- src/weather_routing_pi.h
Fix use SVG graphics macros to use SVG
Fix OCPN API version number
> Upgrade to API 1.16 for finding shared data location

- po/weather_routing_pi.pot
- src/ReportDialog.cpp
- src/SettingsDialog.cpp
- src/WeatherRouting.cpp
Apparently, Crowdin has a string length limit of about 512 characters.
> Rearrange some strings that exceed Crowdin's max length

- src/RouteMapOverlay.cpp
> Ensure strings are translatable.

- po/weather_routing_pi.pot
- src/RouteMap.cpp
Not so few calculation error messages wasn't marked for translation. Pls check so I haven't missed any purpose for this.
If merged, I will update Crowdin with this new pot file for a possible intermediate release when the translators are as finished as possible.
> Make error message translatable. Edit strings to make translation easier

- src/RouteMap.cpp
- src/WeatherRoutingUI.cpp
> Improved i18n messages

- include/WeatherRoutingUI.h
- src/ConfigurationDialog.cpp
- src/WeatherRoutingUI.cpp
> Remove per-second time step.

- include/RouteMap.h
Intermediate PR to format code comments in doxygen format.
> Doxygen code comment format

- src/WeatherRouting.cpp
- src/WeatherRoutingUI.cpp
> Add tooltip for save as track button. Add popup after operation has completed

- include/LineBufferOverlay.h
- include/PlotDialog.h
- include/Polar.h
- include/PolygonRegion.h
- include/RouteMap.h
- include/RouteMapOverlay.h
- include/SunCalculator.h
- include/WeatherRouting.h
- include/WeatherRoutingUI.h
- src/Boat.cpp
- src/BoatDialog.cpp
- src/ConfigurationDialog.cpp
- src/LineBufferOverlay.cpp
- src/PlotDialog.cpp
- src/Polar.cpp
- src/ReportDialog.cpp
- src/RouteMap.cpp
- src/RouteMapOverlay.cpp
- src/SettingsDialog.cpp
- src/WeatherRouting.cpp
- src/WeatherRoutingUI.cpp
Fix crash/infinite loop when user clicks WR "plot" but there is no data to plot.
Make changes to improve code readability, consistency, and maintainability. The primary changes include:
1. Refactor `Variable` enum. Rename enum values to match standard sailing terms or make the names more meaningful. For example:
1. `WIND_VELOCITY` to `SPEED_THROUGH_WATER`
6. `WIND_VELOCITY_GROUND` to `TRUE_WIND_SPEED `
3. Similarly, rewrite variable labels to make them more intuitive and use standard terminology.
7. Put the enum values and labels together to help code readability.
8. Refactor code such that there is a single array of variable labels instead of three.
9. Provide functions to help match enum to drop-down selection index and make the mapping explicit. Previously the mapping was implicit.
We …
> Jibing count/timing config; Plot improvements

- src/PlotDialog.cpp
> Fix compiler warnings

- src/WeatherRouting.cpp
This is in preparation for https://github.com/OpenCPN/OpenCPN/pull/4459
> Use newer version of the plugin API.

- src/WeatherRouting.cpp
Reverts rgleason/weather_routing_pi#275
> Revert "Use newer version of the plugin API."

- src/WeatherRouting.cpp
> Abbreviate route point names

- src/PlotDialog.cpp
- src/RouteMap.cpp
> [skip ci] Add penalty for sail plan change.

- src/WeatherRouting.cpp
- src/WeatherRoutingUI.cpp
Fixes #114 
cc @rgleason @sebastien-rosset
> Format coordinates consistently

- src/RoutingTablePanel.cpp
- src/WeatherRouting.cpp
I accidentally introduced a dependency on API 1.20. This is to remove that hard dependency and support api 1.18.
> Remove hard dependency on API 1.20

- src/RouteMap.cpp
- src/RouteMapOverlay.cpp
> Add missing includes.

- include/AboutDialog.h
- include/Boat.h
- include/BoatDialog.h
- include/ChargeSource.h
- include/ConfigurationBatchDialog.h
- include/ConfigurationDialog.h
- include/EditPolarDialog.h
- include/FilterRoutesDialog.h
- include/GribRecordSet.h
- include/LineBufferOverlay.h
- include/PlotDialog.h
- include/Polar.h
- include/PolygonRegion.h
- include/ReportDialog.h
- include/RouteMap.h
- include/RouteMapOverlay.h
- include/SettingsDialog.h
- include/StatisticsDialog.h
- include/SunCalculator.h
- include/Utilities.h
- include/weather_routing_pi.h
> Cleanup headers

- include/ConstraintChecker.h
- src/ConstraintChecker.cpp
- src/Position.cpp
- src/RoutePoint.cpp
This PR refactors the constraint checking logic in the weather routing plugin to improve code organization and maintainability. The changes extract constraint validation logic from various places into centralized methods in the ConstraintChecker class.
This helps to reduce the amount of code duplication. This will make it easier to implement RFEs such as #332 and #333
> Refactor navigation and weather constraints.

- include/ConstraintChecker.h
- include/RouteMap.h
- include/RoutePoint.h
- src/ConstraintChecker.cpp
- src/Position.cpp
- src/RoutePoint.cpp
1. Create constraint function for Max True Wind
2. Create constraint function for Max Apparent Wind
3. Create constraint function for Wind versus Current.
4. Create `GetBestPolarAndBoatSpeed` helper function to reduce code duplication.
5. Refactor `Position::Propagate()` and `Position::PropagateToEnd()` to leverage the new `GetBestPolarAndBoatSpeed ` function.
Working to make the `Position::Propagate` and `RoutePoint::PropagateToPoint` converge in terms of constraint validation.
There are some discrepancies which I think are because originally some code was copy/pasted, and then later features were added in one function but not the other. For example, the `RoutePoint::PropagateToPoint` function does not validate the "Wind vs current" constraint: 
```c++
if …
```
> Refactor navigation and weather constraints

- include/RoutePoint.h
- src/Position.cpp
- src/RoutePoint.cpp
- src/WeatherDataProvider.cpp
Regression after #347 . The number of tacks and jibes was incorrect.
> Fix regression in Position data

- README.md
This is mainly a test to check whether I've fixed up my git workflow and can once again submit sane PR's.  Can be merged or not.  Not important.
> Fix main repo name in README

- include/Utilities.h
- src/WeatherRouting.cpp
> Normalize longitude when exporting route

- include/IsoRoute.h
- include/Position.h
- include/RouteMap.h
- include/RoutePoint.h
- include/RoutingTablePanel.h
- include/WeatherDataProvider.h
- src/IsoRoute.cpp
- src/Position.cpp
- src/RouteMapOverlay.cpp
- src/RoutePoint.cpp
- src/RoutingTablePanel.cpp
- src/WeatherDataProvider.cpp
- src/WeatherRouting.cpp
Enhancement inspired by issue #361 :
1. Add "wind source" and "current source" columns in the weather routing table.
2. Refactor to mask DataMask strong type.
This will help to analyze which data is coming from GRIB, versus which data is coming from climatology.
> Add "wind source" and "current source" columns

- src/WeatherRouting.cpp
This is just https://github.com/rgleason/weather_routing_pi/pull/319 with the commit history cleaned up.
I think it's ready to merge.
cc @sebastien-rosset
> Positions reformatted on the fly on format preference change.

- include/ConstraintChecker.h
- src/ConstraintChecker.cpp
- src/Polar.cpp
- src/RouteMap.cpp
Fix #420 
- Enhanced Land Cache with LRU Management. Converts the existing simple land cache to use LRU (Least Recently Used) eviction.
- Implements bounded cache size to ensure memory does not grow indefinitely.
- Falls back to exact GSHHS calculations only when necessary (near coastlines)
> Improve performance of land cache and ensure cache size is bounded.

- test/CMakeLists.txt
- test/IsoRoute_tests.cpp
- test/PlugIn_Waypoint_mock.h
- test/mock_plugin_api.cpp
- test/mock_plugin_api.h
- test/mock_plugin_impl.c
- test/mock_plugin_impl.cpp
Next iteration of automated testing for weather_routing_pi, starting with IsoRoute class.
Some basic tests have been developed to compile, link and run successfully. Next step is to develop highler level tests, to, for example, run complete weather routings to verify non-regression.
```
cmake -DOCPN_BUILD_TEST=ON -DCMAKE_BUILD_TYPE=Debug ..
make -j12
make test
Running tests...
/opt/homebrew/bin/ctest 
Test project /Users/quinton/src/OpenCPN-dev/weather_routing_pi/build
Start  1: IsoRouteTest.Constructor
1/63 Test  #1: IsoRouteTest.Constructor ......................   Passed    0.02 sec
Start  2: IsoRouteTest.MinimizeLatBasic
2/63 Test  #2: IsoRouteTest.MinimizeLatBasic .................   Passed    0.02 sec
Start  3: IsoRouteTest.IntersectionCountInside
3/63 Test  #3: …
```
> Unit tests for IsoRoute
