include/Boat.h
include/Polar.h
src/Boat.cpp
src/RouteMap.cpp

1. The simulation does not stop just because the next points in the propagation have little or no wind.
2. Implement linear interpolation for light wind conditions (e.g., if boat speed is 2 knots at TWS=4, then at TWS=3, approximate STW=1.5 knots). This means the boat will move very slowly or not at all for as long as the wind is light.
3. If the forecast predicts stronger winds at a later time, the simulation will find a path for the boat to sail towards the destination point.
4. The simulation will eventually stop if the low-wind conditions persist until the end of the forecast in the GRIB file and the destination has not been reached.
This PR is on top of #186 .
Without wind interpolation, the algorithm fails to complete in the following scenarios:
1. Light wind around the starting …

Speed interpolation for low wind conditions

---

include/RouteMap.h
src/RouteMap.cpp

Introduce dynamic time steps, allowing the algorithm to use smaller time increments in critical navigation areas while using larger steps in open water.
1. Added a DetermineDeltaTime() method to dynamically calculate appropriate time steps based on current routing conditions.
2. Smaller time steps when leaving the starting point.
3. Smaller time steps when approaching the destination.
4. Fall back to normal time steps in open water areas.
5. Ensure a minimum time step (60 seconds) to maintain performance.
Follow-up PRs could focus on additional improvements:
1. Smaller steps when there are lots of obstructions (e.g. land)
2. Backtrack with smaller delta time if the propagation failed.
3. Implement adaptive behavior based on local weather conditions (reduce time steps in areas with rapidly …

Initial support for dynamic delta time between isochrons

---

src/PlotDialog.cpp
src/ReportDialog.cpp
src/WeatherRouting.cpp

Fix #168
Use single-digit precision in the routing report for the following properties:
1. Average speed over water.
2. Average speed over ground.
3. Average wind.
4. Maximum wind
5. Average swell.
6. Max swell
7. Max speed
8. Max wind gust
9. Avg current
10. Max current
Plots values:
Route configuration:

Display precision

---

include/ConfigurationDialog.h
include/PolygonRegion.h
include/RouteMap.h
include/RouteMapOverlay.h
include/WeatherRouting.h
include/WeatherRoutingUI.h
include/weather_routing_pi.h
src/ConfigurationDialog.cpp
src/EditPolarDialog.cpp
src/PlotDialog.cpp
src/ReportDialog.cpp
src/RouteMap.cpp
src/RouteMapOverlay.cpp
src/SettingsDialog.cpp
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp
src/weather_routing_pi.cpp

In the Weather Routing Configuration dialog, add radio buttons to select either:
1. "Start from boat" or
2. "Start position" - as selected in drop-down list.
Default selection is "Start position" to maintain backward compatibility
Related issues: #188
1. Create `StartDataType` enum in `RouteConfiguration` to specify whether starting point is from current boat location (e.g. based on position fix), or from specified position (mark).
2. Add radio buttons in the UI to specify "Start From Boat" or start from selected position (mark).
3. In UI initialization, set values of radio buttons based on the RouteConfiguration.
4. When generating route summary, indicate whether the route starts from boat or from selected position.
5. Save/Load `StartType` parameter in configuration file.
6. Add methods …

Add "Start from boat" radio button

---

include/ConfigurationDialog.h
include/RouteMap.h
include/WeatherRouting.h
include/WeatherRoutingUI.h
src/ConfigurationDialog.cpp
src/SettingsDialog.cpp
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp

This is a follow-up PR to #210 
Add a new "Use Current Time for Calculation" checkbox to the route configuration dialog. When enabled, the system automatically uses the current time when the "Compute" button is pressed, eliminating the need to manually update the time before each recalculation during active navigation.
1. Added a new checkbox in the Configuration Dialog to enable automatic current time usage.
2. Time-setting buttons (date/time widget; GRIB Time, Current Time buttons) are automatically disabled when this option is enabled.
3. Implemented the logic to update the calculation start time automatically when computation begins.
4. Save and Load the `UseCurrentTime` attribute to/from the configuration file.
5. Add tooltips.
This enhancement is particularly useful for sailors who …

Add Automatic Current Time Option for Route Calculations

---

include/BoatDialog.h
include/ConfigurationBatchDialog.h
include/RouteMap.h
include/WeatherRouting.h
include/WeatherRoutingUI.h
src/ConfigurationDialog.cpp
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp

Fix for #220 
The Weather Routing plugin currently has two limitations in its save functionality:
1. The "Save" option always shows a file dialog, effectively functioning as a "Save As" operation. This is unintuitive for users who expect standard application behavior where:
1. "Save" updates the current file without prompting
2. "Save As" prompts for a new location
2. In the "Save As" popup, the file is displayed without the file extension (at least on MacOS). If the user clicks the "Save" button, then the file is also named without extension.
3. Users must manually save their work, risking data loss if they forget to save before closing.
Add proper "Save" and "Save As" functionality to match standard application conventions:
1. Renamed the existing OnSave method to OnSaveAs to better …

Add "Save As" functionality and Auto Save to Weather Routing

---

include/WeatherRouting.h
include/WeatherRoutingUI.h
manual/modules/ROOT/pages/index.adoc
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp

Implement some changes listed at https://github.com/rgleason/weather_routing_pi/issues/199#issuecomment-2744972266
Also related to #224
Make the menu item names more intuitive and descriptive of their actual function.
1. Rename "Export" menu item to "Save routing as Track"
2. Rename "Export All" menu item to "Save all routings as Tracks"
3. Rename "ExportRoute" menu item to "Export routing as GPX file"
4. Rename "Configuration" menu to "Routings"
5. Rename "Configuration" panel title to "Routings"
6. Rename "Export" button to  "Save routing as Track"
7. Rename methods and fields accordingly (ease of readability and maintenance).

Improve names of export/save menu items

---

include/ConfigurationDialog.h
include/RouteMap.h
include/WeatherRoutingUI.h
src/ConfigurationDialog.cpp
src/RouteMap.cpp
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp

This PR adds three new efficiency adjustment parameters that allow users to more realistically model sailing performance in different conditions.
1. Added **Upwind Efficiency** parameter to adjust boat speed when sailing toward the wind
2. Added **Downwind Efficiency** parameter to adjust performance when sailing with the wind
3. Added **Night Efficiency** parameter to apply reduced performance during nighttime hours
The **Night Efficiency** parameter is implemented but disabled until a library is available to determine whether a given point is in night time. 
1. Efficiency parameters are applied during isochron propagation to modify calculated boat speeds
2. Upwind/Downwind are determined based on angle between course and true wind
3. Night efficiency uses API calls to determine …

Add upwind/downwind/nighttime efficiency parameters

---

src/Polar.cpp
src/RouteMap.cpp
src/WeatherRouting.cpp

When the true wind speed exceeds the maximum in the polar data but is below the configured safety limit (MaxTrueWindKnots), the algorithm now uses the boat speed for the maximum wind in the polar instead of completely abandoning that routing option.
Related to #198 
Changes:
- Modified Polar::Speed() to use maximum wind in the polar data when wind
is too strong and bound=false parameter is passed
- Updated Position::Propagate() and PropagateToPoint() to handle
POLAR_SPEED_WIND_TOO_STRONG similar to POLAR_SPEED_WIND_TOO_LIGHT
- Changed default safety margin from 100 knots to a more conservative 50 knots
- Clarified code comments to explain the handling of strong wind conditions
Before this PR, the following route completes with failure:
With this PR, the same route completes successfully: …

Improve weather routing in strong wind conditions

---

CMakeLists.txt
include/RouteMap.h
include/SunCalculator.h
po/POTFILES.in
po/POTFILES.in.test
src/ConfigurationDialog.cpp
src/RouteMap.cpp
src/RouteMapOverlay.cpp
src/SunCalculator.cpp
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp

This PR implements a night efficiency parameter that adjusts boat performance during nighttime conditions. The implementation includes:
1. A new SunCalculator class that calculates sunrise and sunset times for any location and date using the US Naval Observatory algorithm from the "Almanac for Computers, 1990" - obtained from OpenCPN core.
2. Enhancements to the route planning system to apply the night efficiency factor when sailing during nighttime hours
Other changes:
3. Moving the ComputeBoatSpeed function from a standalone static function to a method of the RoutePoint class for better organization and encapsulation.
4. Add sanity check in `ComputeBoatSpeed` in case polar index is out of bounds.
Below is a screenshot showing the impact of `NightCumulativeEfficiency`. I've intentionally …

Night efficiency parameter

---

include/RouteMap.h
include/RouteMapOverlay.h
include/WeatherRouting.h
include/WeatherRoutingUI.h
src/RouteMapOverlay.cpp
src/weather_routing_pi.cpp

Fix #112 
1. Make the circle representing the project boat position bigger and thicker.
2. Highlight the isochron matching the selected GRIB time.
3. Add code comments.
Example:
1. The projected boat location is bigger and thicker.
2. The isochron for that selected time is thicker (blue line in this example)

Improve the visibility of the boat indicator in a routing.

---

include/WeatherRouting.h
include/WeatherRoutingUI.h
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp

This is a partial implementation for #224 
Add menu item and button to save "routing" as route.
This is the basic functionality to add a menu and a button. It is functional and makes it possible to activate the route immediately after saving it.
A follow-up PR is needed and is the harder part: Simplify the route while preserving routing constraints, i.e. minimize the number of waypoints.
**Button:**
**Menu Item:**
**Route visible in the "Route and Mark" manager after saving routing.**

Menu and button to Save as route

---

src/WeatherRouting.cpp

This is in preparation for https://github.com/OpenCPN/OpenCPN/pull/4459
This PR should not change any behavior. It uses the new Route API from the OpenCPN plugin API.

Use newer version of the plugin API.

---

CMakeLists.txt
include/RouteMap.h
include/RouteMapOverlay.h
include/WeatherRouting.h
include/WeatherRoutingUI.h
src/ConfigurationDialog.cpp
src/PlotDialog.cpp
src/RouteMap.cpp
src/RouteMapOverlay.cpp
src/SettingsDialog.cpp
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp

Add a "Sail Plan Change Time" parameter to specify a penalty when changing sail plan. This is useful when a boat configuration has multiple polars. This takes into consideration the time it takes to change sail plan and can be used to reduce the total number of sail plan changes.
This parameter has no impact if the boat configuration has a single sail plan.
Create a boat configuration that has multiple polars:
1. Headsail
2. Asymmetric spinnaker
3. Symmetric spinnaker
When creating a route, the navigator may want to control how much time it takes to change the sail plan. A penalty is applied when the sail plan is changed, which tends to reduce the number of sail plan changes.

Add penalty parameter for sail plan change

---

include/WeatherRoutingUI.h
src/ConfigurationDialog.cpp
src/WeatherRouting.cpp
src/WeatherRoutingUI.cpp

Resolves #109 
Fortunately the internal calculations already catered for double values.  Only the user interface component was restricted to integers.  So a fairly easy fix.
Testing:
cc @rgleason @sebastien-rosset

Increase max swell resolution

---

src/WeatherRouting.cpp

While implementing #289 I noticed a bug causing Safety Margin from Land to be truncated to an int when being persisted. 
Before this fix, that configuration setting got chopped to an int.  After this fix, the decimal place gets saved and loaded correctly.
@rgleason @sebastien-rosset FYI

Persist Safety Margin from Land correctly as a double

---

src/WeatherRouting.cpp

On startup, copy the sample `WeatherRoutingConfiguration.xml` config file to plugin data directory if the file does not exist in the target directory.
The regression may have been introduced by https://github.com/rgleason/weather_routing_pi/pull/222

Copy config file if it does not exist

---

src/ConstraintChecker.cpp

Implement cache to improve performance issues identified in #383.
Experimentally, I've found this simple cache provides a ~60% hit cache, which improves performance significantly without major code refactor.

Add cache for land intersection

---

include/RoutingTablePanel.h
include/SunCalculator.h
src/RoutingTablePanel.cpp
src/SunCalculator.cpp
src/WeatherRouting.cpp

Add background color to show time of day  (daylight, dusk/dawn, night). This makes it easier to interpret weather tables.
Enhanced color map based on discussion with @quinton-hoole:

Color code time of day in weather routing table

---

include/BoatDialog.h
include/Utilities.h
include/WeatherRoutingUI.h
src/BoatDialog.cpp
src/WeatherRoutingUI.cpp

1. Each wind speed line has a unique color from a blue-to-red gradient, providing immediate visual feedback about wind speed magnitude.
2. Show tooltip with polar data.
3. Highlight the closest wind line with a thicker pen width.
4. Optimize the size of the polar when "Full Plot" is unchecked. Use as much space as is available in the polar panel. Previously it was optimized for the full polar plot.
5. Add panel showing the interpolated polar data at the cursor.
6. Render icon at the position of the cursor and matching VMG to make it clear what data is displayed in the new "Data at cursor" panel.
7. Show lines with the VMG angle.
https://github.com/user-attachments/assets/2fdd020f-0788-4bf1-8d7c-e953891a89ff

Enhance polar diagram visualization

---

include/ConstraintChecker.h
src/ConstraintChecker.cpp

Address thread safety issues in the segment cache implementation that could lead to race conditions, data corruption, and crashes when multiple isochron propagations run concurrently.
This could happen if the user is triggering multiple isochrone propagations concurrently.

Thread-safe cache

---

include/RouteSimplifier.h
src/RouteSimplifier.cpp

Replaced the unreliable `Contains()` geometric method for finding position times with a more robust approach that uses direct pointer comparison, geometric containment as fallback, and parent chain traversal for positions not found in isochrones. This handles variable time steps between isochrones and destination positions that may be interpolated within isochrone polygons rather than exact propagated points.
Fixes the "Failed to find segment duration" error that prevented route simplification from working.

Route simplification

---

ci/circleci-build-macos-universal.sh

This is a one-liner change to run unit tests in CI on macos. 
Why only macos? Because the other platforms have older versions of CMake which causes the installation of googletest to fail.  It's probably fixable, but hasn't been done yet.
This is not a permanent solution, as the file that has been changed (ci/circleci-build-macos-universal.sh) will be overwritten next time test_plugin gets upgraded, and this PR will be lost. But at least until then we have automatically run unit tests that will indicate regressions automatically.  And it's trivial to make this one-line change in the future again if needed. At some point we should figure out a way to enable per-plugin customization of test_plugin scripts, but I' don't believe that's possible today, and would probably require quite some …

Run unit tests in CI on macos
